// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import MapKit;
@import MessageUI;
@import Foundation;
@import ObjectiveC;
@import CoreLocation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class MKMapView;
@protocol MKAnnotation;
@class MKAnnotationView;
@protocol MKOverlay;
@class MKOverlayRenderer;
@class MKUserLocation;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC16TQGeolocationSDK22DebugMapViewController")
@interface DebugMapViewController : UIViewController <MKMapViewDelegate>
- (void)viewDidLoad;
- (MKAnnotationView * __nullable)mapView:(MKMapView * __nonnull)mapView viewForAnnotation:(id <MKAnnotation> __nonnull)annotation;
- (MKOverlayRenderer * __nonnull)mapView:(MKMapView * __nonnull)mapView rendererForOverlay:(id <MKOverlay> __nonnull)overlay;
- (void)mapView:(MKMapView * __nonnull)mapView didUpdateUserLocation:(MKUserLocation * __nonnull)userLocation;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class MFMailComposeViewController;
@class NSError;
@class UIPickerView;

SWIFT_CLASS("_TtC16TQGeolocationSDK23LogViewerViewController")
@interface LogViewerViewController : UIViewController <UIPickerViewDataSource, UIPickerViewDelegate, MFMailComposeViewControllerDelegate>
- (void)viewDidLoad;
- (void)mailComposeController:(MFMailComposeViewController * __nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * __nullable)error;
- (NSInteger)pickerView:(UIPickerView * __nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * __nonnull)pickerView;
- (NSString * __nullable)pickerView:(UIPickerView * __nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * __nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSNumber (SWIFT_EXTENSION(TQGeolocationSDK))
@end


SWIFT_CLASS("_TtC16TQGeolocationSDK14TQEnvironments")
@interface TQEnvironments : NSObject
+ (NSInteger)Production;
+ (NSInteger)Staging;
+ (NSInteger)QA;
+ (NSInteger)Development;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16TQGeolocationSDK12TQErrorCodes")
@interface TQErrorCodes : NSObject
+ (NSInteger)kErrorResetDatabaseAlreadyExists;
+ (NSInteger)kErrorResetDatabaseNameMandatory;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@protocol TQGeoTrackerDelegate;
@class TQTrigger;

SWIFT_CLASS("_TtC16TQGeolocationSDK12TQGeoTracker")
@interface TQGeoTracker : NSObject
+ (TQGeoTracker * __nonnull)sharedInstance;
- (void)configure:(NSString * __nonnull)appId triggerMode:(NSInteger)triggerMode environment:(NSInteger)environment;
- (void)setParameters:(CLLocationAccuracy)accuracy distanceFilter:(CLLocationDistance)distanceFilter cacheExpiration:(NSInteger)cacheExpiration zoneInterval:(NSNumber * __nonnull)zoneInterval lingerTime:(NSInteger)lingerTime maxLingerTime:(NSInteger)maxLingerTime requestRetryInterval:(NSTimeInterval)requestRetryInterval;
- (void)start;
- (void)stop;
- (void)setTriggerDelegate:(id <TQGeoTrackerDelegate> __nonnull)delegate;
- (NSString * __nonnull)getDeviceId;
- (NSString * __nonnull)getAppId;
- (void)log:(NSString * __nonnull)message;
- (void)reset:(NSString * __nonnull)newDatabaseName success:(void (^ __nonnull)(void))success failure:(void (^ __nonnull)(NSError * __nonnull))failure;
- (NSArray<TQTrigger *> * __nonnull)listTriggers;
@end


SWIFT_PROTOCOL("_TtP16TQGeolocationSDK20TQGeoTrackerDelegate_")
@protocol TQGeoTrackerDelegate
- (void)TQGeoTrackerOnFenceTriggered:(TQGeoTracker * __nonnull)tqGeoTracker trigger:(TQTrigger * __nonnull)trigger;
@end


SWIFT_CLASS("_TtC16TQGeolocationSDK9TQTrigger")
@interface TQTrigger : NSObject
- (NSString * __nonnull)getDeviceId;
- (NSString * __nonnull)getEvent;
- (NSInteger)getTimestamp;
- (NSString * __nonnull)getFenceId;
- (NSString * __nonnull)getFenceName;
@end


SWIFT_CLASS("_TtC16TQGeolocationSDK12TriggerModes")
@interface TriggerModes : NSObject
+ (NSInteger)Both;
+ (NSInteger)LocalOnly;
+ (NSInteger)RemoteOnly;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
